[package]
name = "vaapad"
version = "0.1.0"
authors = ["Jack Shi <shisoftgenius@gmail.com>"]

[dependencies]
vaapad-derive = { path = "vaapad-derive" }
serde = "1.0"
serde_derive = "1.0"
bincode = "*"
erased-serde = "0.3"